### ISSUE TITLE
ocaml-top is not loading the .ocamlinit file

### ISSUE THREAD

**Issue by fourtytwo** [OCamlPro/ocaml-top#53]
Basically what the Title says all the #require ... lines are not loaded

**Comment by lebotlan** [comment]
I have a similar problem: the toplevel_init.ml file is not loaded.

More precisely, if there exists a ~/.ocamlinit file, then toplevel_init.ml is ignored.
To test it, just eval 'stdout == stderr' which is true only if toplevel_init is evaluated.

What happens:
export OCP_DEBUG="1"
ocaml-top
Running "ocaml -init /path/to/toplevel_init.ml -init /homedir/.ocamlinit"...

It seems that ocaml (4.02.1) only handles the last -init file.

However, in top.ml (line 176 of the current version), two -init options may be given to ocaml.
