### ISSUE TITLE
How can I run top level commands in ocaml-top ?

### ISSUE THREAD

**Issue by CreeperLava** [OCamlPro/ocaml-top#62]
I don't see any way to input top level commands (like eg '#load "graphics.cma";;') from the interface of ocaml-top. Is there any trick I'm missing or is this feature simply not implemented ?

**Comment by vrotaru** [comment]
Two options:

- put this and other directives in an `.ocamlinit` file in the directory where you start ocaml-top
- Just put the  line `#load "graphics.cma";;` on top of your file and <Ctrl-e> (evaluate it)

**Comment by CreeperLava** [comment]
Thank you !

**Comment by RogerTarani** [comment]
Maybe you can close this issue?
